# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui

mat = ((df_mat['Qt_acertos'].sum())/(24*100))*100
print('mat = ',int(mat),'%')


por =  ((df_por['Qt_acertos'].sum())/(18*100))*100
print('por = ',int(por),'%')


geo = ((df_geo['Qt_acertos'].sum())/(8*100))*100
print('geo = ',int(geo),'%')


ing = ((df_ing['Qt_acertos'].sum())/(8*100))*100
print('ing = ',int(ing),'%')


his = ((df_his['Qt_acertos'].sum())/(8*100))*100
print('his = ',int(his),'%')


fis = ((df_fis['Qt_acertos'].sum())/(12*100))*100
print('fis = ',int(fis),'%')


qui = ((df_qui['Qt_acertos'].sum())/(12*100))*100
print('qui = ',int(qui),'%')

mat =  49 %
por =  40 %
geo =  42 %
ing =  47 %
his =  45 %
fis =  44 %
qui =  45 %

In [3]:
# 2) Seu código aqui
df2= df_mat['Qt_acertos'] + df_por['Qt_acertos'] + df_geo['Qt_acertos'] + df_ing['Qt_acertos'] + df_his['Qt_acertos'] + df_fis['Qt_acertos'] + df_qui['Qt_acertos'] 
df2

0     35
1     48
2     50
3     32
4     30
      ..
95    34
96    27
97    40
98    40
99    42
Name: Qt_acertos, Length: 100, dtype: int32

In [4]:
# 3) Seu código aqui
df1= ((df_mat['Qt_acertos'] + df_por['Qt_acertos'] + df_geo['Qt_acertos'] + df_ing['Qt_acertos'] + df_his['Qt_acertos'] + df_fis['Qt_acertos'] + df_qui['Qt_acertos'])/90)*100
df1

0     38.888889
1     53.333333
2     55.555556
3     35.555556
4     33.333333
        ...
95    37.777778
96    30.000000
97    44.444444
98    44.444444
99    46.666667
Name: Qt_acertos, Length: 100, dtype: float64

In [5]:
# 4) Seu código aqui
df3 = df1.loc[df1[:]>45]
df3.to_frame(name='Passaram')

     Passaram
1   53.333333
2   55.555556
5   55.555556
7   54.444444
8   64.444444
11  47.777778
12  46.666667
17  57.777778
18  55.555556
20  58.888889
24  55.555556
27  55.555556
29  48.888889
31  60.000000
34  50.000000
35  53.333333
36  62.222222
37  57.777778
39  54.444444
40  52.222222
42  53.333333
44  47.777778
45  53.333333
48  61.111111
50  47.777778
51  46.666667
52  45.555556
53  50.000000
55  45.555556
60  53.333333
62  51.111111
67  51.111111
68  47.777778
70  68.888889
71  58.888889
72  55.555556
75  46.666667
77  58.888889
78  73.333333
80  50.000000
81  61.111111
82  47.777778
83  46.666667
88  55.555556
89  70.000000
93  62.222222
99  46.666667

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [6]:
# seu código aqui
df = df_mat
df['portugues'] = df_por
df['geografia'] = df_geo
df['inglês'] = df_ing
df['história'] = df_his
df['física'] = df_fis
df['química'] = df_qui
df

    Qt_acertos  portugues  geografia  inglês  história  física  química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

In [7]:
df_elim = df[(df_mat['Qt_acertos'] == 0 ) |
              (df_qui['Qt_acertos'] == 0) |
               (df_fis['Qt_acertos']==0 ) ]
df_elim

    Qt_acertos  portugues  geografia  inglês  história  física  química
3           10          7          3       4         0       0        8
6            6          0          7       7         5       0        4
10          10          8          3       2         1       7        0
12          20          8          3       7         1       0        3
14           7         11          1       7         1       4        0
20          23         11          6       5         6       2        0
25           0          4          7       4         0       4        8
26          11         14          6       2         7       0        0
27          21         13          1       5         7       3        0
33          14          8          0       5         6       6        0
35          11         14          6       3         3       0       11
49           8          1          1       0         1       0        8
56           7          6          7       5         6       0        8
65           1          8          2       4         3       0        6
66           5          4          3       6         3       0       10
72          11         16          3       4         7       0        9
73           1         16          2       4         3       0       11
74           9         11          0       7         5       7        0
84          15          1          0       5         1       0        4
89          23         11          7       7         6       9        0
92          14         10          1       6         1       8        0
94           0          5          2       6         1       3        8
98           0         10          3       1         5      10       11

In [8]:
# o número de eliminados é 23 
df_elim.count()

Qt_acertos    23
portugues     23
geografia     23
inglês        23
história      23
física        23
química       23
dtype: int64

In [9]:
df_elim['geografia'].mean()

3.217391304347826

In [10]:
df_elim['história'].mean()

3.4347826086956523

In [11]:
df_pass = df[(df_mat['Qt_acertos'] > 0 ) |
              (df_qui['Qt_acertos'] > 0) |
               (df_fis['Qt_acertos'] > 0 ) ]
df_pass

    Qt_acertos  portugues  geografia  inglês  história  física  química
0            6          7          7       3         1       8        3
1           19         10          0       0         0      11        8
2           14         16          0       5         7       4        4
3           10          7          3       4         0       0        8
4            7          2          2       7         0       9        3
..         ...        ...        ...     ...       ...     ...      ...
95           6          4          7       1         4       9        3
96           8          1          4       6         1       4        3
97          23          5          0       2         4       1        5
98           0         10          3       1         5      10       11
99          11         15          0       1         6       7        2

[100 rows x 7 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?

In [12]:
arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'

In [13]:
# 1) Sua solução aqui
df_vac = pd.read_csv(arquivo)  
df_vac

HTTPError: HTTP Error 403: Forbidden

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 3) solução alternativa

In [ ]:
# 4)

In [ ]:
# 5)

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [ ]:
# 1)

In [ ]:
# 2)

In [ ]:
# 3)

In [ ]:
# 4)

In [ ]:
# 5)